name: FSL
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow
  - bottleneck
  - cmocean
  - python-dateutil
  - jupyterlab
  - matplotlib
  - xarray
  - numpy
  - pandas
  - parcels
  - pip
  - python=3
  - pytz
  - scipy
  - ffmpeg
  - IPython
  - cartopy